

CREATE TABLE ITENS (
 ID CHAR(10) NOT NULL,
 DESCRICAO VARCHAR(1000),
 IMAGEM_ITEM VARCHAR(500),
 QUANTIDADE CHAR(4)
);

ALTER TABLE ITENS ADD CONSTRAINT PK_ITENS PRIMARY KEY (ID);


CREATE TABLE USUARIOS (
 ID  NUMERIC(30) NOT NULL,
 E-MAIL VARCHAR(200) NOT NULL,
 SENHA VARCHAR(10),
 TIPO CHAR(1),
 APELIDO VARCHAR(30)
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID );


CREATE TABLE COMPRADOR (
 ID_Usuario  NUMERIC(30) NOT NULL
);

ALTER TABLE COMPRADOR ADD CONSTRAINT PK_COMPRADOR PRIMARY KEY (ID_Usuario );


CREATE TABLE INSTITUICAO (
 ID_INSTITUICAO  NUMERIC(30) NOT NULL
);

ALTER TABLE INSTITUICAO ADD CONSTRAINT PK_INSTITUICAO PRIMARY KEY (ID_INSTITUICAO );


CREATE TABLE PREGAO (
 ID CHAR(10) NOT NULL,
 ID_INSTITUICAO  NUMERIC(30) NOT NULL,
 DATA_HORA_INICIAL TIMESTAMP(10),
 DATA_HORA_FINAL TIMESTAMP(10),
 ATIVO BIT(10),
 DESCRICAO_PREGAO VARCHAR(10),
 NOME_LEILAO VARCHAR(40)
);

ALTER TABLE PREGAO ADD CONSTRAINT PK_PREGAO PRIMARY KEY (ID);


CREATE TABLE PREGAO_ITENS (
 ID NUMERIC(30) NOT NULL,
 QUANTIDADE NUMERIC(4),
 VALOR_ATUAL FLOAT(10),
 VALOR_INICIAL FLOAT(10),
 ENTREGUE BIT(10),
 PAGO BIT(10),
 ID_ITEM CHAR(10) NOT NULL,
 ID_PREGAO CHAR(10)
);

ALTER TABLE PREGAO_ITENS ADD CONSTRAINT PK_PREGAO_ITENS PRIMARY KEY (ID);


CREATE TABLE LANCES (
 ID CHAR(10) NOT NULL,
 ID_COMPRADOR NUMERIC(30) NOT NULL,
 ID_PREGAO_ITEM NUMERIC(30) NOT NULL,
 DATAHORA_LANCE TIMESTAMP(10),
 VALOR_LANCE FLOAT(10)
);

ALTER TABLE LANCES ADD CONSTRAINT PK_LANCES PRIMARY KEY (ID);


ALTER TABLE COMPRADOR ADD CONSTRAINT FK_COMPRADOR_0 FOREIGN KEY (ID_USUARIOS ) REFERENCES USUARIOS (ID );


ALTER TABLE INSTITUICAO ADD CONSTRAINT FK_INSTITUICAO_0 FOREIGN KEY (ID_INSTITUICAO ) REFERENCES USUARIOS (ID );


ALTER TABLE PREGAO ADD CONSTRAINT FK_PREGAO_0 FOREIGN KEY (ID_INSTITUICAO ) REFERENCES INSTITUICAO (ID_INSTITUICAO );


ALTER TABLE PREGAO_ITENS ADD CONSTRAINT FK_PREGAO_ITENS_0 FOREIGN KEY (ID_ITEM) REFERENCES ITENS (ID);
ALTER TABLE PREGAO_ITENS ADD CONSTRAINT FK_PREGAO_ITENS_1 FOREIGN KEY (ID_PREGAO) REFERENCES PREGÃO (ID);


ALTER TABLE LANCES ADD CONSTRAINT FK_LANCES_0 FOREIGN KEY (ID_COMPRADOR) REFERENCES COMPRADOR (ID_Usuario );
ALTER TABLE LANCES ADD CONSTRAINT FK_LANCES_1 FOREIGN KEY (ID_PREGAO_ITEM) REFERENCES PREGAO_ITENS (ID);


